services:
  postgres:
    container_name: tr_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - tr-net
    restart: unless-stopped

  pgadmin:
    container_name: tr_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - tr-net
    restart: unless-stopped

  mongodb:
    container_name: tr_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    container_name: tr_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  rabbitmq:
    image: rabbitmq:management
    container_name: tr_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

#  mail-dev:
#    container_name: tr_mail_dev
#    image: maildev/maildev
#    ports:
#      - 1080:1080
#      - 1025:1025

  redis:
    container_name: tr_redis
    image: "bitnami/redis:latest"
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  tr-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  rabbitmq_data: