spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      port: 27017
      authentication-database: admin
      database: bookings
      auto-index-creation: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 6000


logging:
  level:
    org.springframework.data.redis: DEBUG

server:
  port: 8060