spring:
  data:
    mongodb:
      username: user
      password: password
      database: customers
      host: localhost
      port: 27017
      authentication-database: admin
      auto-index-creation: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    customer-creation: customer.creation.queue
  exchange:
    name: internal.exchange
  routing-key:
    customer-creation: internal.customer.routing-key

server:
  port: 8090