spring:
  data:
    mongodb:
      username: user
      password: password
      database: customers
      host: localhost
      port: 27017
      authentication-database: admin
      auto-index-creation: true
server:
  port: 8090