spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: customerServiceCB
                fallbackUri: forward:/fallback/customer
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCB
                fallbackUri: forward:/fallback/auth
        - id: booking-service-aircraft
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/aircraft/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: bookingServiceCB
                fallbackUri: forward:/fallback/booking
        - id: booking-service-flights
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/flights/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: bookingServiceCB
                fallbackUri: forward:/fallback/booking
        - id: booking-service-airports
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/airports/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: bookingServiceCB
                fallbackUri: forward:/fallback/booking
server:
  port: 8222

application:
  security:
    jwt:
      secret-key: YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=

logging:
  level:
    com.arshmed.gateway.config: DEBUG
